# Generated by Django 3.2.4 on 2021-09-21 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Forme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateField()),
                ('date_publication', models.DateField()),
                ('description', models.TextField()),
                ('intitule', models.CharField(max_length=60)),
                ('nombre', models.PositiveIntegerField(default=1)),
                ('experience_min', models.PositiveIntegerField(default=0)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.annonce')),
                ('categories', models.ManyToManyField(related_name='domaines', to='myapi.Categorie')),
                ('forme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.forme')),
                ('villes', models.ManyToManyField(related_name='lieux', to='myapi.Ville')),
            ],
        ),
    ]
